[package]
name = "idb-parser-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = {version="1.0.136", features = ["derive"]}
bincode = "1.3.3"
derivative = "2.2.0"
enumflags2 = {version="0.7.3", features = ["serde"]}
byteorder = "1.4.3"